### ISSUE TITLE
Make Multichain Contact Form Functional

### ISSUE THREAD

**Issue by bunthius** [tksventures/mv-landingpage#2]
## Problem
Contact form at the bottom of the page is currently non-functional and needs to send a message to our designated email.

## Solution

- [x] @tks-wagner @Gallred please provide the email address that multichain contact inquiries will be received
- [ ] hookup the contact form with our standard email service used in other apps, here is the reference contact form: https://tksventures.github.io/mv-landingpage/

**Comment by Gallred** [comment]
Let's use support@multichain.ventures for the web form across all three sites... for now.  Once we have domains configured for EDEN and Cubed, we'll configure a basic support email for each.

**Comment by Gallred** [comment]
Let's use support@multichain.ventures for the web form across all three sites... for now.  Once we have domains configured for EDEN and Cubed, we'll configure a basic support email for each.

**Comment by Gallred** [comment]
Additionally, we need to tie any inquiries that submit the contact form to our SendGrid...

i.e., if they submit the contact form, can we capture their email to our list?
