### ISSUE TITLE
Full opacity on mobile hamburger and menu close button

### ISSUE THREAD

**Issue by bunthius** [tksventures/mv-landingpage#22]
- [x] Change mobile hamburger button and mobile menu close button to be full opacity
extra credit
- [x] always hide menu after hitting a nav link on mobile menu.

**Comment by michalmikolajczyk** [comment]
is this somehow related to #23 ?

**Comment by bunthius** [comment]
Yes, forgot to resolve in the PR, but closing now since it's merged. Thanks.
