### ISSUE TITLE
Subscribe button w/ Klaviyo integration

### ISSUE THREAD

**Issue by Gallred** [tksventures/mv-landingpage#3]
We need a way to get users added to an email list - GDA will be taking this over and using it as one point of our IEO sales funnel.  

We are now using Klaviyo - https://www.klaviyo.com

I have added Jacob as an admin - @bravetarget , it should be in your Tokes email.

You will need to create a snippet via "Signup Forms"

I'd like each page to redirect to a separate segment, one per website (multichain, tokes, eden, cubed, etc.)

Similar issue:
https://github.com/tksventures/cubed-landingpage/issues/3#issue-500484733
https://github.com/tksventures/eden-landingpage/issues/3#issue-500485242
https://github.com/tksventures/tokes-landingpage/issues/1#issue-500485859

**Comment by bunthius** [comment]
@tksventures/engineers this form is ready for engineering. See image below, I left the two notifications of success and failure as `display: block` but the default state should be `display: none` until showing the notification is relevant. 

![image](https://user-images.githubusercontent.com/6615043/66091273-180d0c80-e555-11e9-9a93-227bd3ea5d9b.png)

**Comment by bunthius** [comment]
This code is not publishing to the live site atm. Here's the error from github pages in the settings.

![image](https://user-images.githubusercontent.com/6615043/66165621-2154b280-e603-11e9-8036-d7705db13d3b.png)
